version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    platform: linux/amd64
    command: redis-server --requirepass default
    environment:
      REDIS_USER: ${DEFAULT_VALUE}
      REDIS_PASSWORD: ${DEFAULT_VALUE}
    ports:
      - "6379:6379"
    restart: unless-stopped

  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://host.docker.internal:5678/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "3000:3000"
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    platform: linux/amd64
    environment:
      WEBHOOK_URL: http://host.docker.internal:5678
      N8N_HOST: host.docker.internal
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    restart: unless-stopped

volumes:
  waha_sessions:
  waha_media:
  n8n_data:
